EXECUTE DBMS_STATS.GATHER_TABLE_STATS('RETAILDW','WMD_LOCATION');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('RETAILDW','INVENT_DIM');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('RETAILDW','SALES');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('RETAILDW','INVENT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('RETAILDW','GENERAL_PURCH_CONTRACT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('RETAILDW','INVENT_MODULE');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('RETAILDW','WMD_UNIT_CONVERT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('RETAILDW','GENERAL_PURCH_CONTRACTITEM');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('RETAILDW','UNITCONVERT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('RETAILDW','WMD_LOCATION');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('RETAILDW','WMD_EXCISE');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('RETAILDW','STAGE_PRICEDISCTABLE');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('RETAILDW','SALES_FACT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('RETAILDW','CUSTOMER_ACCOUNT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('RETAILDW','STATION');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('RETAILDW','MODE_OF_TRANSPORT');




